### ISSUE TITLE
Return object from onChange

### ISSUE THREAD

**Issue by The-Code-Monkey** [affinipay/react-bootstrap-autosuggest#19]
when i give an array such as [{ id: 1, name: "test"}]

when i select an item i need it to return the object not just the name how do i do this or why isnt this the default way of doing it?

**Comment by trevorr** [comment]
You need to enable `valueIsItem`, as shown in the [demo](https://affinipay.github.io/react-bootstrap-autosuggest/#items-as-values).

It's not the default because it generally requires a little extra setup to define how to construct objects for input values that didn't come from the `datalist` (assuming you're not using `datalistOnly`). For example, see the [documentation for the `onChange` event](https://github.com/affinipay/react-bootstrap-autosuggest/blob/master/src/Autosuggest.js#L268) regarding how `valueIsItem` changes its behavior.
