### ISSUE TITLE
Specify a minimum length for autocomplete

### ISSUE THREAD

**Issue by viridia** [affinipay/react-bootstrap-autosuggest#3]
A feature that some other autocomplete widgets have: don't start matching until the user has typed at least N characters (in my case, since I'm searching over a large list of email addresses, it's pretty useless to start searching when they type 'a' - I'll probably set the minimum token length to 2 or 3).

**Comment by trevorr** [comment]
Do you need this for a static or dynamic datalist? For dynamic datalists, I felt any such constraints are best handled in the `onSearch` handler (as shown in the [demo](https://affinipay.github.io/react-bootstrap-autosuggest/#onsearch)). For static datalists, there didn't seem to be any harm in autocompleting from the first character, since maybe the one the user wants will happen to be visible in the dropdown menu. Therefore, I've resisted adding such an attribute, but I could be swayed. (If it were added, I'm not sure how it should interact with `onSearch`.)

**Comment by viridia** [comment]
Hey, thanks for the response - I went ahead and implemented my own autocomplete widget (after trying out about 4 different ones) so I'm no longer looking at this.
